language: php
dist: trusty
php:
  - 7.1
before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --no-interaction --dev
after_script:
  - vendor/bin/test-reporter --coverage-report=build/coverage/coverage.xml