version: '3'

services:
  webserver-dev:
    hostname: webserver-dev
    build:
      context: ./containers/webserver-dev
      args:
        user_id: 1000
        group_id: 1000
    image: inmock-webserver-dev
    volumes:
      - .:/var/www:rw
    networks:
      - inmock-dev
    ports:
      - 4000:80

networks:
  inmock-dev:
    ipam:
      driver: default
      config:
        - subnet: 172.12.0.0/29
