parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    InMockBundle\:
        resource: '../../src/InMockBundle/*'
        exclude: '../../src/InMockBundle/{Entity,Repository}'

    InMockBundle\Controller\:
        resource: '../../src/InMockBundle/Controller'
        public: true
        tags: ['controller.service_arguments']